{
  "license": "CC Attribution-NonCommercial-ShareAlike 4.0 International",
  "license-text": "https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt",
  "title": "The Crypto Crossword",
  "by": "SHILLhouse",
  "clues": [
    { "d":"A", "n":2, "x":7, "y":0, "a":"AUGUR", "c":"Birdwatcher" },
    { "d":"A", "n":5, "x":13, "y":1, "a":"BITCOIN", "c":"Digital gold" },
    { "d":"A", "n":7, "x":5, "y":2, "a":"POPULOUS", "c":"Full of people" },
    { "d":"A", "n":10, "x":16, "y":3, "a":"VERGE", "c":"Very close" },
    { "d":"A", "n":11, "x":2, "y":4, "a":"TETHER", "c":"Fastener" },
    { "d":"A", "n":13, "x":10, "y":5, "a":"ELASTIC", "c":"Band material" },
    { "d":"A", "n":14, "x":19, "y":5, "a":"IOTA", "c":"Not one ____" },
    { "d":"A", "n":15, "x":3, "y":6, "a":"KOMODO", "c":"Type of dragon" },
    { "d":"A", "n":18, "x":11, "y":7, "a":"RIPPLE", "c":"Disturbance" },
    { "d":"A", "n":21, "x":3, "y":8, "a":"WINGS", "c":"Flight tools" },
    { "d":"A", "n":23, "x":18, "y":9, "a":"TRIGGERS", "c":"Squeeze these" },
    { "d":"A", "n":25, "x":12, "y":10, "a":"GULDEN", "c":"Digital gold, to the Dutch" },
    { "d":"A", "n":26, "x":1, "y":11, "a":"ARAGON", "c":"Brian Eno song" },
    { "d":"A", "n":27, "x":10, "y":12, "a":"ARDOR", "c":"Passion" },
    { "d":"A", "n":29, "x":0, "y":13, "a":"METAL", "c":"Put the pedal to it" },
    { "d":"A", "n":31, "x":16, "y":13, "a":"STATUS", "c":"Standing" },
    { "d":"A", "n":32, "x":10, "y":15, "a":"NEO", "c":"Took the red pill" },
    { "d":"D", "n":1, "x":3, "y":0, "a":"LYKKE", "c":"Good feeling, to a Norwegian" },
    { "d":"D", "n":3, "x":9, "y":0, "a":"GOLEM", "c":"Brought to life" },
    { "d":"D", "n":4, "x":6, "y":1, "a":"MONERO", "c":"Coin, to Zamenhof" },
    { "d":"D", "n":6, "x":16, "y":1, "a":"CIVIC", "c":"Japanese car" },
    { "d":"D", "n":8, "x":12, "y":2, "a":"STRATIS", "c":"Cake components, to a Catholic" },
    { "d":"D", "n":9, "x":20, "y":2, "a":"MELON", "c":"Pepo" },
    { "d":"D", "n":12, "x":25, "y":4, "a":"GNOSIS", "c":"Knowledge, to a Hellenist" },
    { "d":"D", "n":16, "x":5, "y":6, "a":"MONACO", "c":"Typeface" },
    { "d":"D", "n":17, "x":7, "y":6, "a":"DASH", "c":"Get there quickly" },
    { "d":"D", "n":19, "x":14, "y":7, "a":"PILLAR", "c":"Roof holder" },
    { "d":"D", "n":20, "x":21, "y":7, "a":"EDGELESS", "c":"Blunt" },
    { "d":"D", "n":22, "x":16, "y":9, "a":"NEXUS", "c":"Connection" },
    { "d":"D", "n":24, "x":1, "y":10, "a":"WAVES", "c":"Surfboard holders" },
    { "d":"D", "n":28, "x":11, "y":12, "a":"RISE", "c":"What Jesus did on the third day" },
    { "d":"D", "n":30, "x":3, "y":13, "a":"ARK", "c":"Where the animals went" }
  ]
}
